[ClassVersion("1.0.0.0"), FriendlyName("xTimeZone")]
class xTimeZone : OMI_BaseResource
{
    [Key, Description("Specifies the Target"), ValueMap{"localhost"}, Values{"localhost"}] String Target;
    [Required, Description("Specifies the TimeZone.")] String TimeZone;
};



